
- name: Setup environment
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Influxdb server
  hosts: influxdbservers
  become: yes
  roles:
    - { role: influxdb, tags: ['influxdb'] }

- name: Setup telegraf agents
  hosts: all
  become: yes
  roles:
    - { role: telegraf, tags: [ 'telegraf'] }
